---
version: "3.3"

services:
  app:
    container_name: app-test
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - COMMIT
    depends_on:
      - postgres

  postgres:
    image: postgres:10-alpine
    container_name: postgres-test
    environment:
      POSTGRES_DB: drupal
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
