---
- name: Check if stable and latest version are the same
  fail:
    msg: Stable and latest versions should be the same
  when: stable != latest

- name: Cleanup
  shell: "docker container prune -f"
  args:
    chdir: /var/www/html/

- name: Start blue service
  shell: "docker-compose up --build -d blue"
  args:
    chdir: /var/www/html/

- name: Return error if we are in release phase
  shell: "docker-compose ps | grep -c blue"
  args:
    chdir: /var/www/html/
  register: result
  failed_when: result.stdout == "0"

- name: Switch upstream from green to blue
  shell: docker rename upstream green && docker rename blue upstream

- name: Stop slave server
  shell: docker-compose stop green
  args:
    chdir: /var/www/html/
